language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-ntp.gemspec
- gem install sensu-plugins-ntp-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: gwnrJa1dxCPXRbM1iquvYJFwyN225XjJI/4E8fteWf9D0ZAF3Vks7sOUvCqOjwXMmHds1viH0ilVlCuKcNqs/joOL5ggpzg56sZVBaB7fWdJncjvXLmCi0lkU/oI2f0GBESoCw13cGEzGFZ67EGq7X3VmmMx2V3Gwn3zr5BPdyk=
  gem: sensu-plugins-ntp
  on:
    tags: true
    repo: sensu-plugins/sensu-plugins-ntp
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
